name: Test
on: [ push ]
jobs:

  test:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11 ] # list of os: https://github.com/actions/virtual-environments
        go: [ '1.18' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-${{ matrix.os }}-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}

      - run: GODEBUG=cgocheck=2 go test -race -gcflags=all=-d=checkptr -v ./...

      - name: Race
        run: make race

  win:
    strategy:
      matrix:
        os: [ windows-2019 ] # list of os: https://github.com/actions/virtual-environments
        go: [ '1.18' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - run: choco upgrade mingw cmake -y --no-progress
      - run: go test -v ./...
